package com.mycompany.g07_ejercicio_03_06;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gus-Gus
 */
public class Ventana extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form Ventana1
     */
    public Ventana() {
        initComponents();
        this.addMouseListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtFigura = new javax.swing.JLabel();
        comboBoxFig = new javax.swing.JComboBox<>();
        txtColor = new javax.swing.JLabel();
        comboBoxColor = new javax.swing.JComboBox<>();
        lblAncho = new javax.swing.JLabel();
        txtAncho = new javax.swing.JTextField();
        txtAlto = new javax.swing.JTextField();
        lblAlto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        txtFigura.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        txtFigura.setText("SELECCIONE LA FIGURA: ");

        comboBoxFig.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        comboBoxFig.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxFig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Triangulo", "Rectangulo", "Circulo", "Estrella", "Cuadrado" }));

        txtColor.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        txtColor.setText("SELECCIONE EL COLOR:");

        comboBoxColor.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        comboBoxColor.setForeground(new java.awt.Color(255, 255, 255));
        comboBoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Amarillo", "Rojo", "Verde" }));
        comboBoxColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxColorActionPerformed(evt);
            }
        });

        lblAncho.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        lblAncho.setText("SELECCIONE EL ANCHO: ");

        txtAncho.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N

        txtAlto.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N

        lblAlto.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        lblAlto.setText("SELECCIONE EL ALTO:");

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 3, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DIBUJAR FIGURA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI Light", 3, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NUEVA FIGURA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1163, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Pristina", 2, 36)); // NOI18N
        jLabel1.setText("TABLERO DE DIBUJO");

        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxColor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFigura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxFig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAncho, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAncho, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(txtAlto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(btnSalir)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAncho)
                    .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlto)
                    .addComponent(txtFigura)
                    .addComponent(comboBoxFig, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        figurasList.clear();
        this.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
                figura=new Figura();

                figura.setTipo(comboBoxFig.getSelectedItem()+"");
                
                if(comboBoxColor.getSelectedItem().equals("Amarillo"))
                {
                    figura.setColor(Color.YELLOW);
                }else if (comboBoxColor.getSelectedItem().equals("Azul"))
                {
                    figura.setColor(Color.BLUE);
                }else if(comboBoxColor.getSelectedItem().equals("Rojo"))
                {
                    figura.setColor(Color.RED);
                }else if(comboBoxColor.getSelectedItem().equals("Verde"))
                {
                    figura.setColor(Color.GREEN);
                }
                figura.setAlto(Integer.valueOf(txtAncho.getText()));
                figura.setAncho(Integer.valueOf(txtAlto.getText()));
                figurasList.add(figura);
            }catch(Exception g)
            {
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxColorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

  
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    private static ArrayList<Figura> figurasList=new ArrayList<>();
    private Figura figura;
    private Point punto;
    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        try{
            for(int i=0;i<figurasList.size();i++)
            {
                
                Figura figura=figurasList.get(i);
                if(figura.getTipo().equals("Rectangulo"))
                {
                    g.setColor(figura.getColor());
                    int ancho=figura.getAncho();
                    int alto=figura.getAlto();
                    ancho+=figura.getPunto().x;
                    alto+=figura.getPunto().y;
                    int puntoX=(figura.getPunto().x)-((ancho-figura.getPunto().x)/2);
                    int puntoY=(figura.getPunto().y)-((alto-figura.getPunto().y)/2);
                    int anchoX=(ancho)-((ancho-figura.getPunto().x)/2);
                    int altoY=(alto)-((alto-figura.getPunto().y)/2);
                    g.fillRect(puntoX,puntoY,figura.getAlto(),figura.getAncho());
                    
                    
                }else if(figura.getTipo().equals("Triangulo"))
                    
                {
                    g.setColor(figura.getColor());
                    int ancho=figura.getAncho();
                    int alto=figura.getAlto();
                    ancho+=figura.getPunto().x;
                    alto+=figura.getPunto().y;
                    
                    int puntoX=(figura.getPunto().x)-((ancho-figura.getPunto().x)/2);
                    int puntoY=(figura.getPunto().y)-((alto-figura.getPunto().y)/2);
                    int anchoX=(ancho)-((ancho-figura.getPunto().x)/2);
                    int altoY=(alto)-((alto-figura.getPunto().y)/2);
                    
                    int x1=puntoX+(anchoX-puntoX)/2;
                    int y1=puntoY;
                    int x2=puntoX;
                    int y2=altoY;
                    int x3=anchoX;
                    int y3=altoY;
                    
                    int[] puntosX={x1,x2,x3};
                    int[] puntosY={y1,y2,y3};
                    
                    g.fillPolygon(puntosX,puntosY,3);
                    
                }else if(figura.getTipo().equals("Circulo"))
                {
                    g.setColor(figura.getColor());
                    
                    int ancho=figura.getAncho();
                    int alto=figura.getAlto();
                    
                    ancho+=figura.getPunto().x;
                    alto+=figura.getPunto().y;
                    
                    int puntoX=(figura.getPunto().x)-((ancho-figura.getPunto().x)/2);
                    int puntoY=(figura.getPunto().y)-((alto-figura.getPunto().y)/2);
                    int anchoX=(ancho)-((ancho-figura.getPunto().x)/2);
                    int altoY=(alto)-((alto-figura.getPunto().y)/2);
                    
                    g.fillOval(puntoX,puntoY,figura.getAncho(),figura.getAlto());
                    
                }else if(figura.getTipo().equals("Estrella"))
                {
                    g.setColor(figura.getColor());
                    
                    int ancho=figura.getAncho();
                    int alto=figura.getAlto();
                    
                    ancho+=figura.getPunto().x;
                    alto+=figura.getPunto().y;
                    
                    int puntoX=(figura.getPunto().x)-((ancho-figura.getPunto().x)/2);
                    int puntoY=(figura.getPunto().y)-((alto-figura.getPunto().y)/2);
                    int anchoX=(ancho)-((ancho-figura.getPunto().x)/2);
                    int altoY=(alto)-((alto-figura.getPunto().y)/2);
                    
                    int x1=(puntoX+anchoX)/2;
                    int y1=puntoY;
                    
                    int x2=(puntoX)+(((anchoX-puntoX)/25)*9);
                    int y2=(puntoY)+((((altoY)-(puntoY))/5)*2);
                    
                    int x3=puntoX;
                    int y3=(puntoY)+((((altoY)-(puntoY))/5)*2);;
                    
                    int x4=(puntoX)+(((anchoX-puntoX)/25)*7);
                    int y4=(puntoY)+((((altoY)-(puntoY))/25)*16);
                   
                    int x5=((puntoX)+((anchoX-puntoX)/5));
                    int y5=altoY;
                    
                    int x6=(puntoX)+((anchoX-puntoX)/2);
                    int y6=(puntoY)+((((altoY)-(puntoY))/5)*4);
                    
                    int x7=(puntoX)+(((anchoX-puntoX)/5)*4);
                    int y7=altoY;
                    
                    int x8=(puntoX)+(((anchoX-puntoX)/25)*18);
                    int y8=(puntoY)+((((altoY)-(puntoY))/25)*16);
                    
                    int x9=anchoX;
                    int y9=(puntoY)+((((altoY)-(puntoY))/5)*2);;
                    
                    int x10=(puntoX)+(((anchoX-puntoX)/25)*16);
                    int y10=(puntoY)+((((altoY)-(puntoY))/5)*2);
                   
                    int[] puntosX={x1,x2,x3,x4,x5,x6,x7,x8,x9,x10};
                    int[] puntosY={y1,y2,y3,y4,y5,y6,y7,y8,y9,y10};
                    
                    g.fillPolygon(puntosX,puntosY,10);
                    
                
               }else if(figura.getTipo().equals("Cuadrado"))
                
                {
                    g.setColor(figura.getColor());
                    int ancho=figura.getAncho();
                    int alto=figura.getAlto();
                    ancho+=figura.getPunto().x;
                    alto+=figura.getPunto().y;
                    int puntoX=(figura.getPunto().x)-((ancho-figura.getPunto().x)/2);
                    int puntoY=(figura.getPunto().y)-((alto-figura.getPunto().y)/2);
                    int anchoX=(ancho)-((ancho-figura.getPunto().x)/2);
                    int altoY=(alto)-((alto-figura.getPunto().y)/2);
                    g.fillRect(puntoX,puntoY,figura.getAlto(),figura.getAncho());
            }
            }
        }catch(Exception e)
        {
        }
        
        
        
    }
    @Override
    public void mouseClicked(MouseEvent e) {
        try{
            punto=new Point();
            punto=e.getPoint();
            System.out.println(punto);
            figurasList.get(figurasList.size()-1).setPunto(punto);
            this.repaint();
        }catch(Exception f)
        {
            System.out.println("La lista esta vacia");
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
        System.out.print("");
    }

    @Override
    public void mouseReleased(MouseEvent e) {
        System.out.print("");
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        System.out.print("");
    }

    @Override
    public void mouseExited(MouseEvent e) {
        System.out.print("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboBoxColor;
    private javax.swing.JComboBox<String> comboBoxFig;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAlto;
    private javax.swing.JLabel lblAncho;
    private javax.swing.JTextField txtAlto;
    private javax.swing.JTextField txtAncho;
    private javax.swing.JLabel txtColor;
    private javax.swing.JLabel txtFigura;
    // End of variables declaration//GEN-END:variables
    
    
}
